export const pets = [
  {
    id: 1,
    name: "Cogote",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-juegos-mentales-perro-cachorro.png.webp?itok=i2FAaVxg",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "3 meses",
    breed: "Golden Retriever",
    goodWithDogs: true,
    goodWithCats: false,
    neutered: false,
    vaccinated: true,
  },
  {
    id: 2,
    name: "Rita",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-como-hidratar-a-un-perro-3_0.png.webp?itok=ALWt1Mkn",
    imageAlt: "Pet image",
    sex: "Hembra",
    age: "6 meses",
    breed: "Labrador Retriever",
    goodWithDogs: false,
    goodWithCats: true,
    neutered: true,
    vaccinated: true,
  },
  {
    id: 3,
    name: "Sultán",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/lugar-acogedor-gato.jpg.webp?itok=vtDyKID7",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "1 año",
    breed: "Gato doméstico",
    goodWithDogs: true,
    goodWithCats: true,
    neutered: true,
    vaccinated: false,
  },
  {
    id: 4,
    name: "Pepita",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/ideas-de-nombres-para-gatos-y-su-significado-1.jpg.webp?itok=y5gIH55B",
    imageAlt: "Pet image",
    sex: "Hembra",
    age: "2 años",
    breed: "Gato doméstico",
    goodWithDogs: false,
    goodWithCats: false,
    neutered: false,
    vaccinated: false,
  },
  {
    id: 5,
    name: "Rex",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-juegos-mentales-perro-cachorro.png.webp?itok=i2FAaVxg",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "4 meses",
    breed: "Labrador Retriever",
    goodWithDogs: true,
    goodWithCats: true,
    neutered: false,
    vaccinated: true,
  },
  {
    id: 6,
    name: "Mia",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-como-hidratar-a-un-perro-3_0.png.webp?itok=ALWt1Mkn",
    imageAlt: "Pet image",
    sex: "Hembra",
    age: "1 año",
    breed: "Golden Retriever",
    goodWithDogs: false,
    goodWithCats: true,
    neutered: true,
    vaccinated: true,
  },
  {
    id: 7,
    name: "Max",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/lugar-acogedor-gato.jpg.webp?itok=vtDyKID7",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "2 años",
    breed: "Gato doméstico",
    goodWithDogs: true,
    goodWithCats: false,
    neutered: true,
    vaccinated: true,
  },
  {
    id: 8,
    name: "Luna",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-juegos-mentales-perro-cachorro.png.webp?itok=i2FAaVxg",
    imageAlt: "Pet image",
    sex: "Hembra",
    age: "1 año",
    breed: "Bulldog Francés",
    goodWithDogs: true,
    goodWithCats: true,
    neutered: true,
    vaccinated: true,
  },
  {
    id: 9,
    name: "Rocky",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-como-hidratar-a-un-perro-3_0.png.webp?itok=ALWt1Mkn",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "4 años",
    breed: "Pastor Alemán",
    goodWithDogs: true,
    goodWithCats: false,
    neutered: false,
    vaccinated: true,
  },
  {
    id: 10,
    name: "Nina",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/lugar-acogedor-gato.jpg.webp?itok=vtDyKID7",
    imageAlt: "Pet image",
    sex: "Hembra",
    age: "8 meses",
    breed: "Gato doméstico",
    goodWithDogs: false,
    goodWithCats: true,
    neutered: true,
    vaccinated: true,
  },
  {
    id: 11,
    name: "Simba",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/ideas-de-nombres-para-gatos-y-su-significado-1.jpg.webp?itok=y5gIH55B",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "3 años",
    breed: "Maine Coon",
    goodWithDogs: true,
    goodWithCats: true,
    neutered: true,
    vaccinated: false,
  },
  {
    id: 12,
    name: "Milo",
    href: "#",
    imageSrc:
      "https://www.purina.com.ar/sites/default/files/styles/webp/public/2023-06/purina-juegos-mentales-perro-cachorro.png.webp?itok=i2FAaVxg",
    imageAlt: "Pet image",
    sex: "Macho",
    age: "6 meses",
    breed: "Bulldog Inglés",
    goodWithDogs: true,
    goodWithCats: false,
    neutered: false,
    vaccinated: true,
  },
];
